====== Tag Object as Plant ======
> **Developer:** //FlamingoScript//
> **Summary:** //Demonstrates how to tag an object as a Flamingo nXt plant.//

=====Question=====
How do I tag an object as a Flamingo nXt plant?

=====Answer=====
The following are examples of how to tag an object as a Flamingo nXt plant.

**RhinoScript**
<code vb>
Option Explicit

Call Main()

Sub Main()
	Dim objPlugIn, plantFile, strObject, topiary, location, plant
	On Error Resume Next
	Set objPlugIn = Rhino.GetPluginObject("8008880f-8d13-4b2d-92b0-727e12878a4c")
	If Err Then
		MsgBox Err.Description
		Exit Sub
	End If
  plantFile = objPlugIn.GetPlantFileName("")
  If Not IsNull(plantFile) Then
	  strObject = Rhino.GetObject("Select object to tag as plant")
    If Not IsNull(strObject) And Not strObject = "" Then
      topiary = False
      location = Array(0.0, 0.0, 0.0)
      If objPlugIn.PlantFileNameIsGroundcover(plantFile) Then
        topiary = Rhino.GetBoolean("Plant topiary", Array( "Topiary", "Off", "On"), Array(topiary))
      Else
        location = Rhino.GetPoint("Plant location")
      End If
      If Not IsNull(location) And Not IsNull(topiary) Then
        Set plant = objPlugIn.NewPlant()
        plant.FileName = plantFile
        plant.Location = location
        plant.Topiary = topiary
        If objPlugIn.TagObjectAsPlant(strObject, Plant) Then
            Rhino.Print("Plant " & plantName & " assigned to selected object")
        End If
        Set plant = Nothing
      End If
    End If
	End If
	Set objPlugIn = Nothing
End Sub
</code>

**Python**
<code python>
import clr
# Load the Flamingo nXt SDK DLL
clr.AddReference("FlamingoNXtSDK")
import FlamingoNXtSDK
import rhinoscriptsyntax as rs
import Rhino
# Get the Flamingo nXt plug-in's SDK implimentaion, this will force the
# plug-in to load if it is not currently loaded
flSDK = FlamingoNXtSDK.SDK.FlamingoSDK

def TagObjectAsPlant():
    """ Tags the specified object as a plant """
    # Display the plant file dialog
    result, plantName = flSDK.GetPlantFileName(None, "")
    if not result: return
    # Prompt user to select oject to assign material to
    objID = rs.GetObject("Object to tag as plant")
    if not objID: return
    topiary = False
    location = Rhino.Geometry.Point3d.Origin
    result = False
    if flSDK.PlantFileNameIsGroundcover(plantName):
        result, topiary = Rhino.Input.RhinoGet.GetBool("Topiary", True, "Off", "On", topiary)
    else:
        result, location = Rhino.Input.RhinoGet.GetPoint("Plant location", False)
    if result != Rhino.Commands.Result.Success: return
    # Attempt to tag the specified object as a plant
    sdkPlant = FlamingoNXtSDK.Plant()
    sdkPlant.FileName = plantName
    sdkPlant.Location = FlamingoNXtSDK.Point3D(location.X, location.Y, location.Z)
    sdkPlant.Topiary = topiary
    if flSDK.TagObjectAsPlant(objID, sdkPlant):
        print "Plant \"", plantName, "\" assigned to selected object"

if __name__=="__main__":
    TagObjectAsPlant()
</code>

**C#**
<code c#>
using System;

using Rhino;
using Rhino.Geometry;
using Rhino.DocObjects;
using Rhino.Input;
using Rhino.Commands;

using FlamingoNXtSDK;

partial class Examples
{
  static bool m_Topiary = false;
  static string m_PlantFileTagAsPlant;
  public static Result TagObjectAsPlant(RhinoDoc doc, Rhino.Commands.RunMode mode)
  {
    SDK sdk = SDK.FlamingoSDK;
    if (null == sdk)
      return Rhino.Commands.Result.Failure;
    Result result = Result.Cancel;
    if (sdk.GetPlantFileName(null, ref m_PlantFileTagAsPlant))
    {
      ObjRef objRef = null;
      result = RhinoGet.GetOneObject("Select object to tag as plant", false, ObjectType.None, out objRef);
      if (result == Result.Success && null != objRef)
      {
        Point3d location = new Point3d(0.0, 0.0, 0.0);
        if (sdk.PlantFileNameIsGroundcover(m_PlantFileTagAsPlant))
          result = RhinoGet.GetBool("Topiary", true, "Off", "On", ref m_Topiary);
        else
          result = RhinoGet.GetPoint("Plant location", false, out location);
        if (result == Result.Success)
        {
          Plant sdkPlant = new Plant();
          sdkPlant.FileName = m_PlantFileTagAsPlant;
          sdkPlant.Location = new Point3D(location.X, location.Y, location.Z);
          sdkPlant.Topiary = m_Topiary;
          if (sdk.TagObjectAsPlant(objRef.ObjectId, sdkPlant))
            RhinoApp.WriteLine("Plant \"" + m_PlantFileTagAsPlant + "\" assigned to selected object");
          else
            result = Result.Failure;
        }
      }
    }
    return result;
  }
}
</code>

{{tag>Developer FlamingoScript FlamingoPython CSharp RhinoScript RhinoPython}}
