====== How To: Add a Torus to Rhino ======
> **Developer:** //[[developer:cplusplusplugins|C++]]//, //[[developer:rhinocommon|RhinoCommon]]//
> **Summary:** //Demonstrates how to create a torus using ON_BrepTorus and add it to Rhino.//

For more information on the ON_BrepTorus function, see it's definition in opennurbs_brep.h.

===== C++ =====
<code c++>
CRhinoCommand::result CCommandTest::RunCommand(
        const CRhinoCommandContext& context 
        )
{
  double major_radius = 4.0;
  double minor_radius = 2.0;
  ON_Plane plane( ON_origin, ON_zaxis );
  ON_Circle circle( plane, major_radius );
  ON_Torus torus( circle, minor_radius );
  ON_Brep* brep = ON_BrepTorus( torus );
  if( brep )
  {
    CRhinoBrepObject* torus_object = new CRhinoBrepObject();
    torus_object->SetBrep( brep );
    if( context.m_doc.AddObject(torus_object) )
      context.m_doc.Redraw();
    else
      delete torus_object;
  }
  return CRhinoCommand::success;
}
</code>

===== C# =====
<code c#>
public static Rhino.Commands.Result AddTorus(Rhino.RhinoDoc doc)
{
  const double major_radius = 4.0;
  const double minor_radius = 2.0;

  Rhino.Geometry.Plane plane = Rhino.Geometry.Plane.WorldXY;
  Rhino.Geometry.Torus torus = new Rhino.Geometry.Torus(plane, major_radius, minor_radius);
  Rhino.Geometry.RevSurface revsrf = torus.ToRevSurface();
  if (doc.Objects.AddSurface(revsrf) != Guid.Empty)
  {
    doc.Views.Redraw();
    return Rhino.Commands.Result.Success;
  }
  return Rhino.Commands.Result.Failure;
}
</code>
===== VB.NET =====
<code vb>
Public Shared Function AddTorus(ByVal doc As Rhino.RhinoDoc) As Rhino.Commands.Result
  Const major_radius As Double = 4.0
  Const minor_radius As Double = 2.0

  Dim plane As Rhino.Geometry.Plane = Rhino.Geometry.Plane.WorldXY
  Dim torus As New Rhino.Geometry.Torus(plane, major_radius, minor_radius)
  Dim revsrf As Rhino.Geometry.RevSurface = torus.ToRevSurface()
  If doc.Objects.AddSurface(revsrf) <> Guid.Empty Then
    doc.Views.Redraw()
    Return Rhino.Commands.Result.Success
  End If
  Return Rhino.Commands.Result.Failure
End Function
</code>

===== Python =====
<code python>
import Rhino
import scriptcontext
import System.Guid

def AddTorus():
    major_radius = 4.0
    minor_radius = 2.0

    plane = Rhino.Geometry.Plane.WorldXY
    torus = Rhino.Geometry.Torus(plane, major_radius, minor_radius)
    revsrf = torus.ToRevSurface()

    if scriptcontext.doc.Objects.AddSurface(revsrf)!=System.Guid.Empty:
        scriptcontext.doc.Views.Redraw()
        return Rhino.Commands.Result.Success
    return Rhino.Commands.Result.Failure


if __name__=="__main__":
    AddTorus()
</code>


{{tag>Developer cplusplus rhinocommon}}