====== Transforming Brep Objects ======
> **Developer:** //[[developer:cplusplusplugins|C++]], [[developer:rhinocommon|RhinoCommon]]//
> **Summary:** //Demonstrates how to transform brep, or boundary representation, objects. //

======C++======
===== Method 1 - The Short Way=====

<code c++>
CRhinoCommand::result CCommandTest::RunCommand( const CRhinoCommandContext& context )
{
  CRhinoGetObject go;
  go.SetCommandPrompt( L"Select brep" );
  go.SetGeometryFilter( ON::brep_object );
  go.GetObjects(1,1);
  if( go.CommandResult() != success )
    return go.CommandResult();

  CRhinoObjRef ref = go.Object(0);

  // Simple translation transformation
  ON_Xform xform;
  xform.Translation( ON_3dVector(18,-18,-25) );

  context.m_doc.TransformObject( ref, xform );
  context.m_doc.Redraw();

  return success;
}

</code>

=====Method 2 - The Long Way=====

<code c++>
CRhinoCommand::result CCommandTest::RunCommand( const CRhinoCommandContext& context )
{
  CRhinoGetObject go; 
  go.SetCommandPrompt( L"Select brep" ); 
  go.SetGeometryFilter( ON::brep_object ); 
  go.GetObjects(1,1);
  if( go.CommandResult() != success )
    return go.CommandResult();

  const CRhinoObjRef& ref = go.Object(0);
  const CRhinoObject* obj = ref.Object();
  if( !obj )
    return failure;
  const ON_Brep* brep = ref.Brep();
  if( !brep )
    return failure;
  ON_Brep* dupe = brep->Duplicate();
  if( !dupe )
    return failure;

  // Simple translation transformation
  ON_Xform xform;
  xform.Translation( ON_3dVector(18,-18,-25) );

  if( !dupe->Transform( xform ) )
  {
    RhinoApp().Print( L"Unable to transform object.\n" );
    delete dupe;
    return failure;
  }

  ON_3dmObjectAttributes attribs = obj->Attributes();
  context.m_doc.AddBrepObject( *dupe, &attribs );

  // Since CRhinoDoc::AddBrepObject() make a copy of the input
  // brep, we are responsible for deleting the original. Otherwise
  // we will leak memory;
  delete dupe;
  // Delete the selected object
  context.m_doc.DeleteObject( ref );
  context.m_doc.Redraw();
  return success;
}

</code>

====== RhinoCommon =======

===== C# =====
<code c#>
public static Rhino.Commands.Result TransformBrep(Rhino.RhinoDoc doc)
{
  Rhino.DocObjects.ObjRef rhobj;
  var rc = RhinoGet.GetOneObject("Select brep", true, Rhino.DocObjects.ObjectType.Brep, out rhobj);
  if(rc!= Rhino.Commands.Result.Success)
    return rc;

  // Simple translation transformation
  var xform = Rhino.Geometry.Transform.Translation(18,-18,25);
  doc.Objects.Transform(rhobj, xform, true);
  doc.Views.Redraw();
  return Rhino.Commands.Result.Success;
}
</code>
===== VB.NET =====
<code vb>
Public Shared Function TransformBrep(doc As Rhino.RhinoDoc) As Rhino.Commands.Result
  Dim rhobj As Rhino.DocObjects.ObjRef = Nothing
  Dim rc = RhinoGet.GetOneObject("Select brep", True, Rhino.DocObjects.ObjectType.Brep, rhobj)
  If rc <> Rhino.Commands.Result.Success Then
    Return rc
  End If

  ' Simple translation transformation
  Dim xform = Rhino.Geometry.Transform.Translation(18, -18, 25)
  doc.Objects.Transform(rhobj, xform, True)
  doc.Views.Redraw()
  Return Rhino.Commands.Result.Success
End Function
</code>
===== Python =====
<code python>
import Rhino
import scriptcontext

def TransformBrep():
    rc, objref = Rhino.Input.RhinoGet.GetOneObject("Select brep", True, Rhino.DocObjects.ObjectType.Brep)
    if rc!=Rhino.Commands.Result.Success: return
    
    # Simple translation transformation
    xform = Rhino.Geometry.Transform.Translation(18,-18,25)
    scriptcontext.doc.Objects.Transform(objref, xform, True)
    scriptcontext.doc.Views.Redraw()

if __name__=="__main__":
    TransformBrep()
</code>

{{tag>Developer cplusplus rhinocommon}}